name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3.6.3
        with:
          install: true
          cache: true
      - name: Install dependencies
        run: pnpm install --ignore-scripts
      - name: Build libs
        run: |
          pnpm run build
          pnpm rebuild # To create bin links
      - name: Tests
        run: pnpm run test:coverage
      - name: Upload coverage artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: coverage
          path: ./packages/mcp-server-supabase/coverage/lcov.info
          retention-days: 1
  coveralls:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ always() && needs.test.result == 'success' }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - name: Download coverage artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: coverage
      - name: Upload coverage results to Coveralls
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
        with:
          base-path: ./packages/mcp-server-supabase
          file: lcov.info
